project_id = "mtlycegceaeueuyymkyv"

[functions.strava-auth]
verify_jwt = true

[functions.strava-callback]
verify_jwt = false

[functions.strava-stats]
verify_jwt = true

[functions.strava-stats-batch]
verify_jwt = true

[functions.notify-admin-new-user]
verify_jwt = false
