project_id = "mtlycegceaeueuyymkyv"

[functions.strava-auth]
verify_jwt = true

[functions.strava-callback]
verify_jwt = false

[functions.strava-stats]
verify_jwt = true

[functions.strava-stats-batch]
verify_jwt = true

[functions.notify-admin-new-user]
verify_jwt = false

[functions.push-vapid-keys]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = true

[functions.push-send]
verify_jwt = false

[functions.import-bicycle-routes]
verify_jwt = false

[functions.analyze-routes-page]
verify_jwt = true

[functions.import-selected-routes]
verify_jwt = true

[functions.update-routes-gpx]
verify_jwt = false
